In [1]:
import cv2
cv2.__version__

'4.5.5'

In [3]:
img = cv2.imread("image/smallgray.png")
img

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [4]:
img = cv2.imread("image/smallgray.png",0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [7]:
cv2.imwrite("new_smallgray.jpg",img)

True

In [8]:
cv2.imwrite("image/new_smallgray.png",img)

True

In [9]:
img[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [10]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [14]:
img[2,0]

209

In [15]:
img[2,1]

134

In [16]:
img[0,0]

187

In [18]:
for i in img.T:
   print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [19]:
for i in img.flat:
   print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [22]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
import numpy
ims = numpy.hstack((img,img))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [26]:
ims = numpy.hstack((img,img,img))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [27]:
ims = numpy.vstack((img,img,img))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [33]:
lst = numpy.hsplit(ims,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [36]:
lst = numpy.vsplit(ims,9)
lst

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]

In [39]:
lst = numpy.vsplit(ims,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [41]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)