In [4]:
import numpy
n = numpy.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [5]:
type(n)

numpy.ndarray

In [8]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
type([[123,34,504,309],[],[56,908]])

list

In [15]:
m = numpy.asarray([[123,34,504,309],[],[56,908]])
type(m)

C:\Users\amt\AppData\Local\Temp\ipykernel_7616\3202464734.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m = numpy.asarray([[123,34,504,309],[],[56,908]])


numpy.ndarray

In [2]:
import numpy as np
np.array(4)

array(4)

In [5]:
arr = np.array([4,5])
arr

array([4, 5])

In [6]:
np.zeros(2)

array([0., 0.])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.empty(2)

array([1., 1.])

In [11]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.empty(1)

array([1.94693963e-308])

In [22]:
np.arange(4)

array([0, 1, 2, 3])

In [23]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
np.arange(2, 9, 2)


array([2, 4, 6, 8])

In [25]:
np.arange(2, 9)

array([2, 3, 4, 5, 6, 7, 8])

In [29]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
np.linspace(0, 10, num=7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [31]:
x = np.ones(2, dtype=np.int64)

In [32]:
x

array([1, 1], dtype=int64)

In [33]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])